[package]
name = "oximo"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true
description.workspace = true
readme = "README.md"
keywords.workspace = true
categories.workspace = true

[features]
default = ["io"]
highs = ["dep:oximo-highs"]
io = ["dep:oximo-io"]
gurobi = ["dep:oximo-gurobi"]
mosek = ["dep:oximo-mosek"]
gams = ["dep:oximo-gams"]
baron = ["dep:oximo-baron"]
clarabel = ["dep:oximo-clarabel"]
clarabel-faer = ["clarabel", "oximo-clarabel/faer"]
pounce = ["dep:oximo-pounce"]
pounce-enzyme = ["pounce", "oximo-pounce/enzyme"]
_benchmark-support = [
    "dep:criterion",
    "dep:rayon",
    "highs",
    "io",
    "gams",
    "baron",
    "clarabel",
    "pounce",
    "oximo-core/benchmark-support",
    "oximo-highs/benchmark-support",
    "oximo-io/benchmark-support",
    "oximo-gams/benchmark-support",
    "oximo-baron/benchmark-support",
    "oximo-clarabel/benchmark-support",
    "oximo-pounce/benchmark-support",
]
_benchmark-proprietary = [
    "_benchmark-support",
    "gurobi",
    "mosek",
    "oximo-gurobi/benchmark-support",
    "oximo-mosek/benchmark-support",
]
_benchmark-enzyme = [
    "_benchmark-support",
    "dep:oximo-autodiff",
    "oximo-autodiff/benchmark-support",
    "oximo-autodiff/enzyme",
]

[package.metadata.docs.rs]
features = ["highs", "gams", "baron", "clarabel", "clarabel-faer", "pounce"]
rustdoc-args = ["--cfg", "docsrs"]

[dependencies]
oximo-expr.workspace = true
oximo-core.workspace = true
oximo-solver.workspace = true
oximo-highs = { workspace = true, optional = true }
oximo-gurobi = { workspace = true, optional = true }
oximo-mosek = { workspace = true, optional = true }
oximo-gams = { workspace = true, optional = true }
oximo-baron = { workspace = true, optional = true }
oximo-clarabel = { workspace = true, optional = true }
oximo-pounce = { workspace = true, optional = true }
oximo-io = { workspace = true, optional = true }
oximo-autodiff = { workspace = true, optional = true }
criterion = { workspace = true, optional = true }
rayon = { workspace = true, optional = true }

[lints]
workspace = true

[[bench]]
name = "preprocessing"
harness = false
required-features = ["_benchmark-support"]

[[example]]
name = "baron_robot"
doc-scrape-examples = false

[[example]]
name = "sos"
required-features = ["gurobi"]

[[example]]
name = "indicator"
required-features = ["gurobi"]

[[example]]
name = "sos_reformulated"
required-features = ["highs"]

[[example]]
name = "indicator_reformulated"
required-features = ["highs"]

[[example]]
name = "transport"
required-features = ["highs"]

[[example]]
name = "parametric_pricing"
required-features = ["highs"]

[[example]]
name = "resource_investment_scheduling"
required-features = ["highs"]

[[test]]
name = "solve"
required-features = ["highs"]
